name: Cache from base/default branch

on:
  push:
    branches:
      - main
      - test

jobs:
  cache:
    name: Update Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GITHUB_REF
        run: |
          echo ${GITHUB_REF}
          echo ${{ env.GITHUB_REF }}

      - name: GITHUB_REF_NAME
        run: |
          echo ${GITHUB_REF_NAME}
          echo ${{ env.GITHUB_REF_NAME }}

      - name: Branch is main?
        if: ${{ github.ref == 'ref/heads/main' }}
        run: |
          echo ${GITHUB_REF_NAME}
          echo ${{ env.GITHUB_REF_NAME }}

      - name: Branch is main - alt?
        if: ${GITHUB_REF} == 'ref/heads/main'
        run: |
          echo ${GITHUB_REF_NAME}
          echo ${{ env.GITHUB_REF_NAME }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set-up yarn lock checksum
        id: yarn-lock-checksum
        run: |
          echo ::set-output name=checksum::${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ steps.yarn-lock-checksum.outputs.checksum }}
          restore-keys: |
            yarn-

      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ steps.yarn-lock-checksum.outputs.checksum }}

      - name: Install dependencies
        if: steps.node-modules-cache-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --silent --frozen-lockfile --json --no-progress 2>&1 | tee yarn_install.txt
